"""Add meals meals unique constraint

Revision ID: b15aa58b12eb
Revises: dd2bc8862ea5
Create Date: 2020-08-03 14:53:42.654285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b15aa58b12eb'
down_revision = 'dd2bc8862ea5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('type_date_unique', 'meals', ['type', 'date', 'user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('type_date_unique', 'meals', type_='unique')
    # ### end Alembic commands ###
